-- Local development seed data
-- Run with: pnpm db:seed:local
--
-- IMPORTANT: This file is for local development only.
-- To test locally, uncomment the examples below and replace with your actual Telegram chat ID.
-- Your chat ID can be found by messaging @userinfobot on Telegram.

-- Example: Add yourself as a test user
-- INSERT OR IGNORE INTO users (telegram_chat_id, display_name)
-- VALUES ('123456789', 'Your Name');

-- Example: Create a specific filter (NOT a catch-all)
-- INSERT OR IGNORE INTO filters (
--   user_id, name,
--   min_price, max_price,
--   min_bedrooms, max_bedrooms,
--   cities_json, neighborhoods_json,
--   enabled
-- ) VALUES (
--   1, 'Tel Aviv 2-3BR under 7000',
--   4000, 7000,
--   2, 3,
--   '["תל אביב"]', NULL,
--   1
-- );
